### PR TITLE
Visually hidden menu btn label

### PR DESCRIPTION
**Pull request by naps62**

### CODE REVIEW

**Comment by naps62** [comment]
@zamith is this correct?

**Comment by zamith** [comment]
Not really, because the `display: none` will also make it invisible for SR. Our preferred way in the past has been this:

``` css
.VisuallyHidden
  position: absolute
  width: 1px
  height: 1px
  padding: 0
  border: 0
  margin: -1px
  overflow: hidden
  clip: rect(0 0 0 0)
```

This should work in most scenarios.

**Comment by zamith** [comment]
Actually, because of how the hamburger is implemented, this was a bit trickier. Fixed it in #21.

**Comment by naps62** [comment]
@zamith this can be cancelled in favor of your PR then right?

**Comment by zamith** [comment]
Yes.

**Pull request closed without merging**
