### PR TITLE
Optimize Braga page images

### PR DESCRIPTION
**Pull request by joaojusto**
Converted images from png to jpg and changed quality to 70%

Page load before: 
screen shot 2015-08-24 at 14 55 49

Page load after:
screen shot 2015-08-24 at 14 56 12

### CODE REVIEW

**Comment by zamith** [comment]
Have you put them through `image_optim`, or something similar? This is a good improvement, but I feel we should be able to get the size down, still. 2 megs seems a lot, even though it has a handful of images.

**Comment by joaojusto** [comment]
I will put them through image_optim, but I don't think we can save any more without losing quality.

**Comment by joaojusto** [comment]
@zamith after passing them through `image_optim` I saved more 22kb total. Any ideias on how to improve this? 
screen shot 2015-08-24 at 20 41 18

**Comment by zamith** [comment]
Hum... Maybe someone will come up with a brilliant way of getting this further down, but until then, go ahead and merge so that we get the improvements online. :ship:

**Pull request merged**
